import { createContext, useState, useCallback } from "react";

export const AppContext = createContext();

export const t = {
  en: {
    // Nav
    calculators: "Calculators",
    // Tax names
    tos: "Tax on Salary",
    ppt: "Prepayment Profit Tax",
    plt: "Public Lighting Tax",
    stp: "Specific Tax",
    at: "Accommodation Tax",
    wht: "Withholding Tax",
    // Descriptions
    tosDesc: "Monthly salary tax for employees",
    pptDesc: "1% prepayment on monthly revenue",
    pltDesc: "5% on alcohol & tobacco products",
    stpDesc: "Excise tax 10–35% by category",
    atDesc: "2% on hotel & guesthouse rooms",
    whtDesc: "Tax withheld at source of payment",
    // Calculator labels
    calculate: "Calculate",
    reset: "Reset",
    gross: "Gross",
    net: "Net",
    tax: "Tax",
    monthly: "Monthly",
    annual: "Annual",
    resident: "Resident",
    nonResident: "Non-Resident",
    baseSalary: "Base Salary",
    bonus: "Bonus",
    overtime: "Overtime",
    otherBenefits: "Other Benefits",
    spouse: "Non-working Spouse",
    children: "Qualifying Children",
    childrenHint: "Under 14, or under 25 if full-time student",
    includesVAT: "includes VAT (10%)",
    revenue: "Monthly Revenue",
    productPrice: "Product Price (incl. VAT)",
    category: "Category",
    roomRate: "Room Rate",
    paymentAmount: "Payment Amount",
    paymentType: "Payment Type",
    applyDTA: "Apply DTA Reduced Rate (10%)",
    withheld: "Tax Withheld",
    netPayment: "Net to Recipient",
    effectiveRate: "Effective Rate",
    taxBase: "Prepayment Cal. Base",
    annualEst: "Annual Estimate",
    grossSalary: "Gross Salary",
    deductions: "Deductions",
    taxableIncome: "Taxable Income",
    taxPayable: "Tax Payable",
    netSalary: "Net Salary",
    spouseRebate: "Spouse Rebate",
    childRebate: "Child Rebates",
    exemptMsg: "Exempt — payment under 50,000 KHR (Circular 024, 2026)",
    brackets: "Tax Brackets",
    PPTPayable: "Prepayment Tax (1%)",
    revenueDetails: "Revenue Details (KHR)",
  

    aboutPPT: "About PPT",
    aboutLine1: "Real Regime enterprises pay PPT monthly",
    aboutLine2: "The PPT paid can be credited against the annual Tax on Profit",
    aboutLine3: "QIP companies may qualify for exemption",
    aboutLine4: "Deadline: 20th of following month",
    breakdown: "Breakdown",
    grossRevenue: "Gross Revenue",
    vatComponent: "VAT Component (10%)",
    revenueExclVAT: "Revenue excl. VAT",
    pptRate: "PPT Rate",
    pptPayable: "PPT Payable",
    revenueBreakdown: "Revenue Breakdown",
    enterRevenue: "Enter revenue to calculate PPT",
    formula_ppt: "Tax Base = Revenue / 1.1  (if incl. VAT)\nPPT = Tax Base × 1%\nAnnual = PPT × 12",
    pieRevenue: "Revenue (excl. VAT)",
    pieVAT: "VAT (10%)",
    piePPT: "PPT (1%)",

    calcMode: "Calculation Mode",
    producerImporter: "Producer / Importer",
    resellerWholesale: "Reseller / Wholesale / Retail",
    formula: "Formula",
    formulaProducer: "PLT Base = Product Price - VAT - STP\nPLT Payable = PLT Base × 5%",
    formulaReseller: "PLT Base = (Product Price - VAT - STP) × 20%\nPLT Payable = PLT Base × 5%",
    pltNoteLabel: "Note",
    pltNote: "PLT applies only to alcohol and tobacco products (beer, wine, spirits, tobacco)",
    pltBreakdownChart: "Breakdown",
    pltBreakdown: "BREAKDOWN",
    priceInclVAT: "Price incl. VAT",
    pltBase: "PLT Base",
    pltPayable: "PLT Payable (5%)",
    pltEnterPrice: "Enter product price to calculate PLT",

    stpRateLabel:    "Rate",
    stpRule90:       "90% rule applies for local products",
    stpCalcSteps:    "Calculation Steps",
    stpRate:         "STP Rate",
    stpPriceInclVAT: "Price incl. VAT",
    stpExclVAT:      "excl. VAT",
    stpExclSTP:      "excl. STP",
    stpLocalRule:    "local rule (90%)",
    stpTaxBase:      "Tax Base (90%)",
    stpPayable:      "STP Payable",
    stpPlaceholder:  "Select category and enter price",

    atRoomRateLabel:  "Room Rate incl. VAT (KHR)",
    atNote:           "AT applies to hotels, guesthouses, and serviced apartments in Cambodia",
    atAbout:          "About AT",
    atAboutLine1:     "Applies to accommodation services (hotels, guesthouses)",
    atAboutLine2:     "Flat 2% rate on the tax base",
    atAboutLine3:     "Collected by the accommodation provider",
    atAboutLine4:     "Declared monthly by the 20th",
    atTaxBase:        "Tax Base",
    atPayable:        "AT Payable (2%)",
    atBreakdown:      "Breakdown",
    atCalcSteps:      "Calculation Steps",
    atRoomRateInclVAT:"Room Rate incl. VAT",
    atExclVAT:        "÷ 1.1 (excl. VAT)",
    atDivTaxBase:     "÷ 1.02 (Tax Base)",
    atMulPayable:     "× 2% = AT Payable",
    atPlaceholder:    "Enter room rate to calculate AT",

  
  },
  kh: {
    calculators: "គណនាពន្ធ",
    tos: "ពន្ធលើប្រាក់បៀវត្ស",
    ppt: "ប្រាក់រំដោះពន្ធលើប្រាក់ចំណេញ",
    plt: "អាករបំភ្លឺសាធារណៈ",
    stp: "អាករពិសេស",
    at: "ពន្ធស្នាក់នៅ",
    wht: "ពន្ធកាត់ទុក",
    tosDesc: "ពន្ធប្រចាំខែសម្រាប់និយោជិត",
    pptDesc: "ការបង់ជាមុន ១% លើចំណូល",
    pltDesc: "ពន្ធ ៥% លើស្រា និងបារី",
    stpDesc: "អាករ ១០–៣៥% តាមប្រភេទទំនិញ",
    atDesc: "ពន្ធ ២% លើបន្ទប់សណ្ឋាគារ",
    whtDesc: "ពន្ធកាត់ពីប្រភព",
    calculate: "គណនា",
    reset: "កំណត់ឡើងវិញ",
    gross: "សរុប",
    net: "សុទ្ធ",
    tax: "ពន្ធ",
    monthly: "ប្រចាំខែ",
    annual: "ប្រចាំឆ្នាំ",
    resident: "និវាសនជន",
    nonResident: "អនិវាសនជន",
    baseSalary: "ប្រាក់ខែមូលដ្ឋាន",
    bonus: "ប្រាក់រង្វាន់",
    overtime: "ការងារបន្ថែម",
    otherBenefits: "អត្ថប្រយោជន៍ផ្សេង",
    spouse: "ប្តីឬប្រពន្ធគ្មានប្រាក់ចំណូល",
    children: "ចំនួនកូន",
    childrenHint: "អាយុក្រោម ១៤ ឬក្រោម ២៥ ប្រសិនជានិសិ្សត",
    includesVAT: "តម្លៃរួមទាំង VAT (១០%)",
    revenue: "ចំណូលប្រចាំខែ",
    productPrice: "តម្លៃផលិតផល (រួមបញ្ចូល VAT)",
    category: "ប្រភេទ",
    roomRate: "តម្លៃបន្ទប់",
    paymentAmount: "ចំនួនទូទាត់",
    paymentType: "ប្រភេទការទូទាត់",
    applyDTA: "អនុវត្ត DTA (១០%)",
    withheld: "ពន្ធត្រូវកាត់",
    netPayment: "ទូទាត់សុទ្ធ",
    effectiveRate: "អត្រាពន្ធជាក់ស្ដែង",
    taxBase: "មូលដ្ឋានគិតពន្ធ",
    annualEst: "ការប៉ាន់ប្រចាំឆ្នាំ",
    grossSalary: "ប្រាក់ខែសរុប",
    deductions: "ការកាត់ចេញ",
    taxableIncome: "ប្រាក់ចំណូលជាប់ពន្ធ",
    taxPayable: "ពន្ធត្រូវបង់",
    netSalary: "ប្រាក់ខែសុទ្ធ",
    spouseRebate: "ការបញ្ចុះប្តី/ប្រពន្ធ",
    childRebate: "ការបញ្ចុះកូន",
    exemptMsg: "ត្រូវបានលើកលែង — ក្រោម ៥០,០០០ ៛ (Circular 024, 2026)",
    brackets: "ចំណែកពន្ធ",
    PPTPayable: "ប្រាក់រំដោះពន្ធ​(អាត្រា​​១%)",
    grossSalary: "ប្រាក់ខែសរុប",
    deductions: "ការកាត់កងចេញ",
    taxableIncome: "ប្រាក់ចំណូលជាប់ពន្ធ",
    taxPayable: "ពន្ធត្រូវបង់",
    netSalary: "ប្រាក់ខែសុទ្ធ",
    spouseRebate: "ការបញ្ចុះសម្រាប់ប្ដីឬប្រពន្ធ",
    childRebate: "ការបញ្ចុះសម្រាប់កូន",
    brackets: "តារាងចំណែកពន្ធ",

    revenueDetails: "ព័ត៌មានលម្អិតអំពីប្រាក់ចំណូល (រៀល)",
    aboutPPT: "អំពីប្រាក់រំដោះពន្ធ",
    aboutLine1: "សហគ្រាសដែលស្ថិតក្រោមរបបពិតប្រាកដ ត្រូវបង់ប្រាក់រំដោះពន្ធប្រចាំខែ",
    aboutLine2: "ប្រាក់ PPT ដែលបានបង់អាចយកទៅកាត់ពីពន្ធលើប្រាក់ចំណេញប្រចាំឆ្នាំបាន",
    aboutLine3: "ក្រុមហ៊ុន QIP អាចមានសិទ្ធិទទួលបានការលើកលែង",
    aboutLine4: "កាលបរិច្ឆេទកំណត់៖ ថ្ងៃទី២០ នៃខែបន្ទាប់",
    breakdown: "សង្ខេបលម្អិត",
    grossRevenue: "ចំណូលសរុប",
    vatComponent: "ផ្នែក VAT (១០%)",
    revenueExclVAT: "ចំណូលមិនរួម VAT",
    pptRate: "អត្រាពន្ធ PPT",
    pptPayable: "ពន្ធ PPT ត្រូវបង់",
    revenueBreakdown: "ការបំបែកចំណូល",
    enterRevenue: "បញ្ចូលចំណូលដើម្បីគណនា PPT",
    formula_ppt: "មូលដ្ឋានគិតពន្ធ = ផលរបររួមទាំង អ.ត.ប / ១.១  \nប្រាក់រំដោះពន្ធលើប្រាក់ចំណូល = មូលដ្ឋានពន្ធ × ១%\nប្រាក់រំដោះពន្ធលើប្រាក់ចំណូលប្រចាំឆ្នាំ = ប្រាក់រំដោះពន្ធលើប្រាក់ចំណូល × ១២",
    pieRevenue: "ចំណូល (មិនរួម VAT)",
    pieVAT: "VAT (១០%)",
    piePPT: "PPT (១%)",

    calcMode: "របៀបគណនា",
    producerImporter: "អ្នកផលិត / អ្នកនាំចូល",
    resellerWholesale: "អ្នកលក់បន្ត / លក់ដុំ / លក់រាយ",
    formula: "រូបមន្ត",
    formulaProducer: "មូលដ្ឋានគិតអាករ = តម្លៃផលិតផល - VAT - អាករបំភ្លឺ(STP)\nអាករត្រូវបង់  = មូលដ្ឋានគិតអាករ × ៥%",
    formulaReseller: "មូលដ្ឋានគិតអាករ = (តម្លៃផលិតផល - VAT - អាករបំភ្លឺ(STP)) × ២០%\nអាករត្រូវបង់ = មូលដ្ឋានគិតអាករ × ៥%",
    pltNoteLabel: "កំណត់សម្គាល់",
    pltNote: "PLT អនុវត្តចំពោះផលិតផលស្រា និងបារីប៉ុណ្ណោះ (ស្រាបៀរ ស្រាទំពាំងបាយជូរ​​​ ស្រាគ្រប់ប្រភេទ បារី)",
    pltBreakdownChart: "ព័ត៌មានសង្ខេប",
    pltBreakdown: "ព័ត៌មានលម្អិត",
    priceInclVAT: "តម្លៃផលិតផលរួម VAT",
    pltBase: "មូលដ្ឋានគិតអាករ",
    pltPayable: "អាករត្រូវបង់ (៥%)",
    pltEnterPrice: "បញ្ចូលតម្លៃនៃផលិតផលដើម្បីគណនា PLT",

    stpRateLabel:    "អត្រា",
    stpRule90:       "វិធាន ៩០% អនុវត្តចំពោះផលិតផលក្នុងស្រុក",
    stpCalcSteps:    "ជំហានគណនា",
    stpRate:         "អត្រាអាករពិសេស",
    stpPriceInclVAT: "តម្លៃរួមបញ្ចូល VAT",
    stpExclVAT:      "មិនរួមបញ្ចូល VAT",
    stpExclSTP:      "មិនរួមបញ្ចូល STP",
    stpLocalRule:    "សម្រាប់ផលិតផលក្នុងស្រុក (៩០%)",
    stpTaxBase:      "មូលដ្ឋានគិតអាករពិសេស",
    stpPayable:      "ប្រាក់អាករពិសេសត្រូវបង់",
    stpPlaceholder:  "ជ្រើសប្រភេទ ហើយបញ្ចូលតម្លៃ",

    atRoomRateLabel:  "តម្លៃបន្ទប់រួម VAT (រៀល)",
    atNote:           "ពន្ធស្នាក់នៅអនុវត្តចំពោះសណ្ឋាគារ គេហដ្ឋានស្នាក់នៅ និងអាផាតមិនក្នុងប្រទេសកម្ពុជា",
    atAbout:          "អំពីអាករលើការស្នាក់នៅ",
    atAboutLine1:     "អនុវត្តចំពោះសេវាកម្មស្នាក់នៅ (សណ្ឋាគារ ផ្ទះសំណាក់)",
    atAboutLine2:     "អត្រាអាករ ២% លើមូលដ្ឋានគិតអាករ",
    atAboutLine3:     "ប្រមូលដោយអ្នកផ្តល់សេវាកម្មស្នាក់នៅ",
    atAboutLine4:     "ប្រកាសជាប្រចាំខែត្រឹមថ្ងៃទី ២០",
    atTaxBase:        "មូលដ្ឋានអាករ",
    atPayable:        "អាត្រាអាករស្នាក់នៅ(២%)",
    atBreakdown:      "សង្ខេបលម្អិត",
    atCalcSteps:      "ជំហានគណនា",
    atRoomRateInclVAT:"តម្លៃបន្ទប់រួម VAT",
    atExclVAT:        "មិនរួមបញ្ចូល VAT",
    atDivTaxBase:     "មូលដ្ឋានពន្ធ",
    atMulPayable:     "× ២% = ពន្ធស្នាក់នៅ",
    atPlaceholder:    "បញ្ចូលតម្លៃបន្ទប់ដើម្បីគណនាពន្ធ",
  },
};

export function AppProvider({ children }) {
  const [dark, setDark] = useState(false);
  const [lang, setLang] = useState("en");
  const [currency, setCurrency] = useState("KHR");
  const [exchangeRate] = useState(4100);

  const tr = useCallback((key) => t[lang][key] || key, [lang]);

  const fmt = useCallback((amount) => {
    if (currency === "USD") {
      const usd = amount / exchangeRate;
      return `$${usd.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
    }
    return `${Math.round(amount).toLocaleString("en-US")} ៛`;
  }, [currency, exchangeRate]);

  return (
    <AppContext.Provider value={{ dark, setDark, lang, setLang, currency, setCurrency, tr, fmt, exchangeRate }}>
      {children}
    </AppContext.Provider>
  );
}
